// Blog post manifest — AUTO-GENERATED by blog/sync_manifest.py from the
// frontmatter of blog/<category>/*.md. Do not hand-edit BLOG_POSTS below;
// run `python3 blog/sync_manifest.py` after adding/editing/removing a post
// and commit the regenerated file instead.
//
// `visibility` is copied straight from each post's own frontmatter, so this
// array only controls what appears in listings; blog.html re-reads the
// frontmatter before rendering a post's body, so this file is a listing aid,
// not a security boundary — a private post's raw .md is still a fetchable
// static file like any other.
const BLOG_CATEGORIES = [
  { slug: 'ml-concepts', label: 'ML Concepts' },
  { slug: 'math-stats-notes', label: 'Math &amp; Stats Notes' },
  { slug: 'paper-reviews', label: 'Paper Reviews' },
  { slug: 'essays', label: 'Essays' },
];

const BLOG_POSTS = [
  {
    category: 'ml-concepts',
    categoryLabel: 'ML Concepts',
    slug: 'why-attention-is-normalized-with-softmax',
    title: 'Why Attention Is Normalized with Softmax',
    summary: 'Revisiting softmax\'s role in turning query-key dot products into a probability distribution, alongside the temperature parameter.',
    date: '2026-08-15',
    readTime: '6 min read',
    visibility: 'public',
  },
  {
    category: 'math-stats-notes',
    categoryLabel: 'Math & Stats Notes',
    slug: 'why-kl-divergence-isnt-a-distance',
    title: 'Why KL Divergence Isn\'t a Distance',
    summary: 'Working through asymmetry and the triangle-inequality violation by hand — and why it\'s still the tool of choice.',
    date: '2026-07-28',
    readTime: '4 min read',
    visibility: 'public',
  },
];