#!/usr/bin/env python3
"""Regenerate blog/manifest.js from the frontmatter of blog/<category>/*.md.

Static hosting has no directory listing, so the browser can't discover posts
on its own — manifest.js is what index.html and blog.html read instead. This
script is the fix for keeping it in sync by hand: run it after adding,
editing, or removing any post, and it rebuilds manifest.js from the actual
files on disk, so post counts/titles/visibility can never drift from reality.

Usage:
    python3 blog/sync_manifest.py

Category labels/order come from BLOG_CATEGORIES below — add a line here (and
create the matching folder) when introducing a new category.
"""
import pathlib
import re
import sys

BLOG_DIR = pathlib.Path(__file__).parent
MANIFEST_PATH = BLOG_DIR / "manifest.js"

BLOG_CATEGORIES = [
    ("ml-concepts", "ML Concepts"),
    ("math-stats-notes", "Math &amp; Stats Notes"),
    ("paper-reviews", "Paper Reviews"),
    ("essays", "Essays"),
]

FRONTMATTER_RE = re.compile(r"^---\r?\n(.*?)\r?\n---\r?\n", re.DOTALL)


def parse_frontmatter(text):
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    data = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        data[key.strip()] = value.strip()
    return data


def js_string(value):
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def main():
    category_labels = dict(BLOG_CATEGORIES)
    posts = []

    for slug_dir, label in BLOG_CATEGORIES:
        folder = BLOG_DIR / slug_dir
        if not folder.is_dir():
            continue
        for md_path in sorted(folder.glob("*.md")):
            data = parse_frontmatter(md_path.read_text(encoding="utf-8"))
            missing = [k for k in ("title", "date", "readTime", "summary", "visibility") if k not in data]
            if missing:
                print(f"warning: {md_path} missing frontmatter field(s) {missing}, skipping", file=sys.stderr)
                continue
            category = data.get("category", slug_dir)
            if category != slug_dir:
                print(f"warning: {md_path} frontmatter category '{category}' != folder '{slug_dir}', using folder", file=sys.stderr)
            posts.append({
                "category": slug_dir,
                "categoryLabel": data.get("categoryLabel", category_labels.get(slug_dir, slug_dir)),
                "slug": md_path.stem,
                "title": data["title"],
                "summary": data["summary"],
                "date": data["date"],
                "readTime": data["readTime"],
                "visibility": data["visibility"],
            })

    posts.sort(key=lambda p: p["date"], reverse=True)

    lines = []
    lines.append("// Blog post manifest — AUTO-GENERATED by blog/sync_manifest.py from the")
    lines.append("// frontmatter of blog/<category>/*.md. Do not hand-edit BLOG_POSTS below;")
    lines.append("// run `python3 blog/sync_manifest.py` after adding/editing/removing a post")
    lines.append("// and commit the regenerated file instead.")
    lines.append("//")
    lines.append("// `visibility` is copied straight from each post's own frontmatter, so this")
    lines.append("// array only controls what appears in listings; blog.html re-reads the")
    lines.append("// frontmatter before rendering a post's body, so this file is a listing aid,")
    lines.append("// not a security boundary — a private post's raw .md is still a fetchable")
    lines.append("// static file like any other.")
    lines.append("const BLOG_CATEGORIES = [")
    for slug_dir, label in BLOG_CATEGORIES:
        lines.append(f"  {{ slug: {js_string(slug_dir)}, label: {js_string(label)} }},")
    lines.append("];")
    lines.append("")
    lines.append("const BLOG_POSTS = [")
    for post in posts:
        lines.append("  {")
        for key in ("category", "categoryLabel", "slug", "title", "summary", "date", "readTime", "visibility"):
            lines.append(f"    {key}: {js_string(post[key])},")
        lines.append("  },")
    lines.append("];")
    lines.append("")

    MANIFEST_PATH.write_text("\n".join(lines), encoding="utf-8")
    public_count = sum(1 for p in posts if p["visibility"] == "public")
    print(f"wrote {MANIFEST_PATH} — {len(posts)} post(s) found, {public_count} public")


if __name__ == "__main__":
    main()
