#!/usr/bin/env python3
"""Regenerate static blog metadata and article pages from Markdown frontmatter.

Static hosting has no directory listing, so the browser can't discover posts
on its own — manifest.js is what index.html and blog.html read instead. This
script is the fix for keeping it in sync by hand: run it after adding,
editing, or removing any post, and it rebuilds manifest.js from the actual
files on disk, so post counts/titles/visibility can never drift from reality.

Usage:
    python3 blog/sync_manifest.py

Category labels/order come from BLOG_CATEGORIES below — add a line here (and
create the matching folder) when introducing a new category.
"""
import html
import pathlib
import re
import sys

from generate_rss import absolute_url, generate_rss, site_url

BLOG_DIR = pathlib.Path(__file__).parent
MANIFEST_PATH = BLOG_DIR / "manifest.js"
INDEX_TEMPLATE_PATH = BLOG_DIR / "index.html"
GENERATED_MARKER = "<!-- AUTO-GENERATED by blog/sync_manifest.py -->"

BLOG_CATEGORIES = [
    ("ml-concepts", "ML Concepts"),
    ("math-stats-notes", "Math &amp; Stats Notes"),
    ("paper-reviews", "Paper Reviews"),
    ("essays", "Essays"),
]

FRONTMATTER_RE = re.compile(r"^---\r?\n(.*?)\r?\n---\r?\n", re.DOTALL)


def parse_frontmatter(text):
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    data = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        data[key.strip()] = value.strip()
    return data


def js_string(value):
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def canonical_post_url(base_url, post):
    return f"{base_url}/blog/{post['category']}/{post['slug']}/"


def render_article_page(template, base_url, post):
    """Add crawler-readable article metadata to the shared interactive shell."""
    canonical_url = canonical_post_url(base_url, post)
    title = f"{post['title']} · Jin-Hwa Kim"
    cover = post.get("cover")
    cover_url = absolute_url(cover, base_url, canonical_url) if cover else ""
    card_type = "summary_large_image" if cover_url else "summary"

    metadata = [
        GENERATED_MARKER,
        f'<link rel="canonical" href="{html.escape(canonical_url, quote=True)}">',
        '<meta property="og:type" content="article">',
        f'<meta property="og:title" content="{html.escape(post["title"], quote=True)}">',
        f'<meta property="og:description" content="{html.escape(post["summary"], quote=True)}">',
        f'<meta property="og:url" content="{html.escape(canonical_url, quote=True)}">',
        f'<meta name="twitter:card" content="{card_type}">',
        f'<meta name="twitter:title" content="{html.escape(post["title"], quote=True)}">',
        f'<meta name="twitter:description" content="{html.escape(post["summary"], quote=True)}">',
    ]
    if cover_url:
        escaped_cover = html.escape(cover_url, quote=True)
        metadata.extend([
            f'<meta property="og:image" content="{escaped_cover}">',
            f'<meta name="twitter:image" content="{escaped_cover}">',
        ])

    page = template.replace(
        "<title>Blog · Jin-Hwa Kim</title>",
        f"<title>{html.escape(title)}</title>",
        1,
    )
    page = page.replace("</head>", "\n".join(metadata) + "\n</head>", 1)
    post_key = html.escape(f"{post['category']}/{post['slug']}", quote=True)
    return page.replace("<body>", f'<body data-blog-post="{post_key}">', 1)


def generate_article_pages(posts):
    """Generate public article pages and remove stale generated pages."""
    template = INDEX_TEMPLATE_PATH.read_text(encoding="utf-8")
    base_url = site_url()
    generated_paths = set()

    for post in posts:
        if post["visibility"] != "public":
            continue
        output_path = BLOG_DIR / post["category"] / post["slug"] / "index.html"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(render_article_page(template, base_url, post), encoding="utf-8")
        generated_paths.add(output_path)

    for category, _ in BLOG_CATEGORIES:
        folder = BLOG_DIR / category
        if not folder.is_dir():
            continue
        for output_path in folder.glob("*/index.html"):
            if output_path in generated_paths:
                continue
            if GENERATED_MARKER in output_path.read_text(encoding="utf-8"):
                output_path.unlink()
                try:
                    output_path.parent.rmdir()
                except OSError:
                    pass

    return len(generated_paths)


def main():
    category_labels = dict(BLOG_CATEGORIES)
    posts = []

    for slug_dir, label in BLOG_CATEGORIES:
        folder = BLOG_DIR / slug_dir
        if not folder.is_dir():
            continue
        for md_path in sorted(folder.glob("*.md")):
            data = parse_frontmatter(md_path.read_text(encoding="utf-8"))
            missing = [k for k in ("title", "date", "readTime", "summary", "visibility") if k not in data]
            if missing:
                print(f"warning: {md_path} missing frontmatter field(s) {missing}, skipping", file=sys.stderr)
                continue
            category = data.get("category", slug_dir)
            if category != slug_dir:
                print(f"warning: {md_path} frontmatter category '{category}' != folder '{slug_dir}', using folder", file=sys.stderr)
            post = {
                "category": slug_dir,
                "categoryLabel": data.get("categoryLabel", category_labels.get(slug_dir, slug_dir)),
                "slug": md_path.stem,
                "title": data["title"],
                "summary": data["summary"],
                "date": data["date"],
                "readTime": data["readTime"],
                "visibility": data["visibility"],
            }
            if data.get("cover"):
                post["cover"] = data["cover"]
            posts.append(post)

    posts.sort(key=lambda p: p["date"], reverse=True)

    lines = []
    lines.append("// Blog post manifest — AUTO-GENERATED by blog/sync_manifest.py from the")
    lines.append("// frontmatter of blog/<category>/*.md. Do not hand-edit BLOG_POSTS below;")
    lines.append("// run `python3 blog/sync_manifest.py` after adding/editing/removing a post")
    lines.append("// and commit the regenerated file instead.")
    lines.append("//")
    lines.append("// `visibility` is copied straight from each post's own frontmatter, so this")
    lines.append("// array only controls what appears in listings; blog.html re-reads the")
    lines.append("// frontmatter before rendering a post's body, so this file is a listing aid,")
    lines.append("// not a security boundary — a private post's raw .md is still a fetchable")
    lines.append("// static file like any other.")
    lines.append("const BLOG_CATEGORIES = [")
    for slug_dir, label in BLOG_CATEGORIES:
        lines.append(f"  {{ slug: {js_string(slug_dir)}, label: {js_string(label)} }},")
    lines.append("];")
    lines.append("")
    lines.append("const BLOG_POSTS = [")
    for post in posts:
        lines.append("  {")
        for key in ("category", "categoryLabel", "slug", "title", "summary", "date", "readTime", "visibility"):
            lines.append(f"    {key}: {js_string(post[key])},")
        if post.get("cover"):
            lines.append(f"    cover: {js_string(post['cover'])},")
        lines.append("  },")
    lines.append("];")
    lines.append("")

    MANIFEST_PATH.write_text("\n".join(lines), encoding="utf-8")
    public_count = sum(1 for p in posts if p["visibility"] == "public")
    print(f"wrote {MANIFEST_PATH} — {len(posts)} post(s) found, {public_count} public")
    page_count = generate_article_pages(posts)
    print(f"wrote {page_count} static article page(s)")
    # RSS is a deployment artifact too: allow failures to terminate this
    # command rather than publishing a silently stale or missing feed.
    rss_count = generate_rss()
    print(f"wrote {BLOG_DIR / 'rss.xml'} — {rss_count} public post(s)")


if __name__ == "__main__":
    main()
